version: '3.8'

services:
  service-name1:
    container_name: service-name1
    build:
      dockerfile: Dockerfile
      context: ./service-name1
    ports:
      - "5050:5050"

  service-name2:
    container_name: service-name2
    build:
      dockerfile: Dockerfile
      context: ./service-name2
    ports:
      - "5000:5000"

  web-app:
    container_name: web-app
    build:
      dockerfile: Dcokerfile
      context: ./webapp
    ports:
      - "3000:3000"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "13306:13306"

volumes:
  mongodb_data:
